// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ObservableMonoBehaviour: MonoBehaviour, ObservableObject
{

	private string observer_id;

	protected void OnStart ()
	{
		observer_id = GameObserver.getSingleton().addObservableObject(this);
		//Debug.Log("ObservableMonoBehaviour " + observer_id);
	}

	~ObservableMonoBehaviour(){
		//Debug.Log("~ObservableMonoBehaviour");
		GameObserver.getSingleton().removeObservableObject(observer_id);
	}

	void Start(){
		this.OnStart();
	}

	void OnDestroy(){
		//Debug.Log("ObservableMonoBehaviour OnDestroy");
		GameObserver.getSingleton().removeObservableObject(observer_id);
	}
	
	public virtual void updateMessage(string message, System.Object data, ObservableObject sender)
	{

	}
	
	public virtual void sendMessage(string message, System.Object data)
	{
		GameObserver.getSingleton().notify (message, data,this);
	}
		
		
}


