// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace SpeedX.Utils
{
	public class StringUtils
	{
		private const string _chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
		
		public static string RandomString(int size)
		{
			Random _rng = new Random();
			char[] buffer = new char[size];
			
			for (int i = 0; i < size; i++)
			{
				buffer[i] = _chars[_rng.Next(_chars.Length)];
			}
			return new string(buffer);
		}
	}
}

